[general]
import = ["themes/dracula.toml"]

[colors]
transparent_background_colors = true

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "None"
opacity = 0.98
startup_mode = "Windowed"
