gaps inner 12
gaps outer 3
focus_follows_mouse no
default_border pixel 2
default_floating_border pixel 2

client.focused          #88c0d0 #88c0d0 #ffffff #88c0d0 #88c0d0
client.unfocused        #1f242d #1f242d #7d8590 #1f242d #1f242d
client.focused_inactive #39414d #39414d #d8dee9 #39414d #39414d
client.urgent           #bf616a #bf616a #ffffff #bf616a #bf616a
