assign [app_id="firefox"] workspace number 2
assign [class="firefox"] workspace number 2

for_window [app_id="nm-connection-editor"] floating enable, resize set width 50 ppt height 60 ppt, move position center
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable, resize set width 50 ppt height 60 ppt, move position center
for_window [app_id="thunar"] floating enable, resize set width 58 ppt height 68 ppt, move position center
for_window [class="Nm-connection-editor"] floating enable, resize set width 50 ppt height 60 ppt, move position center
for_window [class="Pavucontrol"] floating enable, resize set width 50 ppt height 60 ppt, move position center
for_window [class="Thunar"] floating enable, resize set width 58 ppt height 68 ppt, move position center
for_window [app_id="org.gnome.PowerStats"] floating enable, resize set width 50 ppt height 60 ppt, move position center
