assign [app_id="firefox"] workspace number 2
assign [class="firefox"] workspace number 2

for_window [app_id="nm-connection-editor"] floating enable, resize set width 960 px height 720 px, move position center
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable, resize set width 980 px height 720 px, move position center
for_window [app_id="thunar"] floating enable, resize set width 1100 px height 750 px, move position center
for_window [class="Nm-connection-editor"] floating enable, resize set width 960 px height 720 px, move position center
for_window [class="Pavucontrol"] floating enable, resize set width 980 px height 720 px, move position center
for_window [class="Thunar"] floating enable, resize set width 1100 px height 750 px, move position center
for_window [app_id="org.gnome.PowerStats"] floating enable, resize set width 960 px height 720 px, move position center
