exec --no-startup-id gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec_always --no-startup-id sh -c 'pkill waybar; exec waybar'
exec --no-startup-id nm-applet --indicator
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
